### ISSUE TITLE
http.Transport

### ISSUE THREAD

**Issue by 89z** [AGWA/tlshacks#1]
Can you use this software to create a Transport:

https://godocs.io/net/http#Transport

that way, you could make a request as a client, with a custom TLS?

**Comment by AGWA** [comment]
No, this isn't a TLS implementation.

**Comment by 89z** [comment]
I see you offer a connection:

https://godocs.io/src.agwa.name/tlshacks#Conn

could that be used? I notice it only has Read method, I guess that means it wouldn't be able to fake anything in regards to sending a request?

**Comment by AGWA** [comment]
No, that type is meant for server-side connections
