### ISSUE TITLE
Module path

### ISSUE THREAD

**Issue by 89z** [AGWA/tlshacks#2]
Is the module set correctly?

https://github.com/AGWA/tlshacks/blob/d2c6f4e2b7804e788e652959f35a05e81f61340f/go.mod#L1

~~~
> curl -I https://src.agwa.name/tlshacks
HTTP/1.1 404 Not Found
Date: Tue, 24 May 2022 21:16:00 GMT
Server: Apache/2.4.53 (Debian)
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Content-Security-Policy: default-src * data: blob: 'unsafe-inline' 'unsafe-eval'
X-XSS-Protection: 0
Content-Type: text/html; charset=iso-8859-1
~~~

Also fails on both doc sites:

- https://godocs.io/src.agwa.name/tlshacks
- https://pkg.go.dev/src.agwa.name/tlshacks

**Comment by AGWA** [comment]
Thanks for report. I've fixed the 404 error, but it appears the Go module proxy has cached the 404. I'm not sure how long until the cache expires.

**Comment by AGWA** [comment]
Everything should be working now.
