### ISSUE TITLE
make response work with utls

### ISSUE THREAD

**Issue by 3052** [AGWA/tlshacks#7]
currently the response from https://tlshello.agwa.name cannot be used with uTLS. with this:

https://pkg.go.dev/github.com/refraction-networking/utls#ClientHelloSpec.FromRaw

it fails because The data should be the full tls record, including the record type/version/length header as well as the handshake type/length/version header

and with these:

https://pkg.go.dev/github.com/refraction-networking/utls#ClientHelloSpec.ImportTLSClientHello
https://pkg.go.dev/github.com/refraction-networking/utls#ClientHelloSpec.ImportTLSClientHelloFromJSON

it fails because the response is a different format

**Comment by 3052** [comment]
https://github.com/refraction-networking/utls/issues/312

**Comment by AGWA** [comment]
The `raw` field contains a Handshake message. I'm not going to change that, but it would be trivial for you to prepend the necessary header to turn it into the TLSPlaintext message expected by the utls package.

**Comment by 3052** [comment]
this seems to fix it:

~~~go
package tlshacks

func prepend(raw []byte) []byte {
   var data []byte
   data = append(data, 22) // record type
   data = append(data, 0, 0) // record version
   data = append(data, 0, 0) // record length
   return append(data, raw...)
}
~~~

**Comment by 3052** [comment]
for another workaround, you can use this with MITM Proxy:

~~~py
import mitmproxy
import logging
import base64

def tls_clienthello(data: mitmproxy.tls.ClientHelloData):
   hello = data.client_hello.raw_bytes()
   logging.info(base64.b64encode(hello))
~~~
